feat: Astro 2741 mat theme update
RocketCommunicationsInc/astro-material-themes pull request #4
Opened 2022-01-24 18:14 UTC by micahjones13

This updates the css/scss to use our tokens where possible. There are a few values that are either opacity based or not in our tokens. For the ones not in our tokens, I also checked figma and could not find them. 

Main changes: 
- Replaced the css files with the current files from our web-components
- Re-minifyed the .min css files (I don't even think they need to exist but I left them just in case)
- Updated the `my-theme` scss files with our token names and updated some values as well. 
- Imported the design token package at root

2022-01-25 14:24 UTC, markacianfrani requested changes

2022-01-25 14:24 UTC, markacianfrani commented on dark/my-theme.scss
> +$color-global-secondary-300: #92cbff; // --primaryLight
can we import these directly from the design-token package?

2022-01-25 14:24 UTC, markacianfrani commented on light/my-theme.scss
> +  $small-component-radius: 3px,
we can use the `--radius-base` token here too

2022-01-25 14:24 UTC, markacianfrani commented on light/my-theme.scss
> +    font-size: 2.125rem,
We can use some of the typography tokens for these: 

```--font-heading-2-font-size```, letter-spacing, weight, etc.

2022-01-26 21:08 UTC, micahjones13 commented on light/my-theme.scss
> +    font-size: 2.125rem,
Done, none of the letter-spacing tokens matched up though.

2022-02-01 17:54 UTC, markacianfrani approved these changes

2022-02-01 17:55 UTC, merged